### PR TITLE
Add nix flake

### PR DESCRIPTION
**Pull request by yavko**
Who doesn't love nix flakes?

### CODE REVIEW

**Comment by ezKEa** [comment]
Hi! thanks for the PR! I noticed your flake includes the only NixOS module, and not the `an-anime-game-launcher` package itself. While this works fine for NixOS users who just want to use the launcher through the module, I feel a proper solution would have the package declared in the `outputs.packages` attribute and passed on to the module (rather than the module importing default.nix as it does now), which would also allow users to build the package from the flake. Perhaps this repo being fully flake-based with [flake-compat](https://github.com/edolstra/flake-compat) for legacy compatibility would be best.

In any case, I plan on flakifying my system soon so I'll be able to give proper consideration to how this should be done then. For the time being, this should be good to merge if you add the launcher to the flake's `outputs.packages` attribute. Thanks!

**Comment by yavko** [comment]
I at first was thinking of also adding a overlay and packages, but in the end decided not too. If you want i can rewrite it completely to be built around flakes.

**Comment by ezKEa** [comment]
It will be fine if you just add a packages attribute with the launcher and its unwrapped version (like in the current default.nix). I can set up flake-compat at a later time.

**Comment by yavko** [comment]
Ight, I'll add it in like an hour, though I'm willing to add flake-compat support if you want since I've done it before.

**Comment by yavko** [comment]
Sorry I had something came up, and wasn't able to do it yesterday as I said, anyway here it is!

**Pull request merged**
